server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log  # for Linux only
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
      - regex:
          expression: ^(?P<image_name>([^|]+))\|(?P<container_name>([^|]+))$
          source: "tag"
      - labels:
          image_name:
          container_name:
      - match:
          selector: '{job="containerlogs",container_name="",image_name=""}'
          action: drop
      - match:
          selector: '{image_name="nginx:stable-alpine3.20-perl"}'
          stages:
            - json:
                expressions:
                  row: log
            - regex:
                expression: .+nginx.+\|.+\[0m(?P<virtual_host>[a-z_\.-]+) +(?P<nginxlog>.+)
                source: logrow
            - regex:
                source: nginxlog
                expression: ^(?P<ip>[\w\.]+) - (?P<user>[^ ]*) \[(?P<timestamp>[^ ]+).*\] "(?P<method>[^ ]*) (?P<request_url>[^ ]*) (?P<request_http_protocol>[^ ]*)" (?P<status>[\d]+) (?P<bytes_out>[\d]+) "(?P<http_referer>[^"]*)" "(?P<user_agent>[^"]*)"( "(?P<response_time>[\d\.]+)")?
            - regex:
                source: request_url
                expression: ^.+\.(?P<static_type>jpg|jpeg|gif|png|ico|css|zip|tgz|gz|rar|bz2|pdf|txt|tar|wav|bmp|rtf|js|flv|swf|html|htm)$
            - regex:
                source: request_url
                expression: ^/photo/(?P<photo>[^/\?\.]+).*$
            - regex:
                source: request_url
                expression: ^/api/(?P<api_request>[^/\?\.]+).*$
            - template:
                source: request_type
                template: "{{if .photo}}photo{{else if .static_type}}static{{else if .api_request}}api{{else}}other{{end}}"
            - labels:
                api_request:
                virtual_host:
                request_type:
                status:
            - output:
                source: nginx_log_row
