services:
  grafana:
    image: grafana/grafana:11.3.1
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana 
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    restart: unless-stopped 
    environment:
      - 'GF_SMTP_ENABLED=${SMTP_ENBL}'
      - 'GF_SMTP_HOST=${SMTP_HOST}'
      - 'GF_SMTP_USER=${SMTP_USER}'
      - 'GF_SMTP_PASSWORD=${SMTP_PASS}'
      - 'GF_SMTP_SKIP_VERIFY=${SMTP_SKIP_VERIFY}'
      - 'GF_SMTP_FROM_NAME=${SMTP_NAME}'
      - 'GF_SMTP_FROM_ADDRESS=${SMTP_USER}'
      - 'GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}'
      - 'GF_SERVER_SERVE_FROM_SUB_PATH=${GF_SERVER_SERVE_FROM_SUB_PATH}'

      - 'GF_AUTH_DISABLE_LOGIN_FORM=${GF_AUTH_DISABLE_LOGIN_FORM}'
      - 'GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}'
      - 'GF_AUTH_ANONYMOUS_ORG_ROLE=${GF_AUTH_ANONYMOUS_ORG_ROLE}'

      - 'GF_USERS_DEFAULT_THEME=${GF_USERS_DEFAULT_THEME}'
    networks:
      - nginx
      - monitoring

  prometheus:
    image: prom/prometheus:v3.0.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules:/etc/prometheus/alert.rules
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.listen-address=:5000'
    networks:
      - monitoring


  alertmanager-bot:
    command:
      - --alertmanager.url=${TG_BOT_URL}
      - --log.level=${TG_BOT_LOG}
      - --store=${TG_BOT_STORE}
      - --bolt.path=${TG_BOT_PATH}
      - --telegram.admin=${TG_BOT_ADMIN}
      - --telegram.token=${TG_BOT_TOKEN}
      - --listen.addr=${TG_BOT_ADDR}
    image: metalmatze/alertmanager-bot:0.4.3
    user: root
    ports:
      - 8888:8888
    container_name: alertmanager-bot
    hostname: alertmanager-bot
    environment:
      TG_BOT_URL: ${TG_BOT_URL}
      TG_BOT_STORE: ${TG_BOT_STORE}
      TG_BOT_PATH: ${TG_BOT_PATH}
      TG_BOT_ADMIN: ${TG_BOT_ADMIN}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      TG_BOT_ADDR: ${TG_BOT_ADDR}
    restart: unless-stopped
    volumes:
      - ./bot-data:/data
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:v0.21.0
    user: root
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    container_name: alertmanager
    hostname: alertmanager
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/etc/alertmanager/data'
    networks:
      - monitoring

  loki:
    image: grafana/loki:3.3.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml -validation.allow-structured-metadata=false
    networks:
      - monitoring
    restart: unless-stopped 

networks:
  monitoring:
    external: true
    name: monitoring-net
  nginx:
    external: true
    name: nginx

volumes:
  prometheus_data: {}
  grafana-storage: {}
