services:

# Приложение
# Все ок
  nginx:
    image: nginx:stable-alpine3.20-perl
    container_name: nginx
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      - monitoring
      - nginx_wordpress
    ports:
      - "80:80"
    depends_on:
      - wordpress
      - keycloak
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
    restart: always

# Работает, но скрипт
  wordpress:
    image: wordpress:6.7.0-php8.1-fpm
    container_name: wordpress
    networks:
      - nginx_wordpress
      - wordpress_db
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', '${REDIS_HOST}');
        define('WP_REDIS_PORT', ${REDIS_PORT});
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    command: >
      sh -c '
        curl -O https://raw.githubusercontent.com/f803/test/refs/heads/main/wordpress.sh &&
        /bin/bash wordpress.sh
      '
    depends_on:
      db:
         condition: service_healthy
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"

# OK
  redis:
    image: redis:alpine3.20
    container_name: redis
    volumes:
      - ./redis/redis.conf:/data/redis.conf
    networks:
      - wordpress_db
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
# OK
  db:
    image: mariadb:11.5.2
    container_name: db
    networks:
      - wordpress_db
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: ${MARIA_DB_RNDM_PASS}
      MARIADB_DATABASE: ${WORDPRESS_DB_NAME}
      MARIADB_USER: ${WORDPRESS_DB_USER}
      MARIADB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      start_period: 10s
      retries: 3
      timeout: 5s

# Экспортеры

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring


# Keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}

#      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_PORT: ${KC_HOSTNAME_PORT}
      KC_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT}
      KC_HOSTNAME_STRICT_HTTPS: ${KC_HOSTNAME_STRICT_HTTPS}

      KC_HTTP_PORT: ${KC_HTTP_PORT}
      KC_LOG_LEVEL: ${KC_LOG_LEVEL}
      KC_METRICS_ENABLED: ${KC_METRICS_ENABLED}
      KC_HEALTH_ENABLED: ${KC_HEALTH_ENABLED}

      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KEYCLOAK_IMPORT: /opt/keycloak/data/import/wordpress.json

      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME: 192.168.4.17/auth
      KC_HTTP_ENABLED: true
      HTTP_ADDRESS_FORWARDING: true
    command: start-dev --hostname-debug=true --import-realm --http-relative-path /auth
    depends_on:
      - keycloakdb
    ports:
      - 8080:8080
    networks:
      - keycloak_network
      - nginx_wordpress
    volumes:
      - ./keycloak/wordpress.json:/opt/keycloak/data/import/wordpress.json:ro
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"


  keycloakdb:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    container_name: keycloak_db
    networks:
      - keycloak_network

#Promtail
  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-data:/var/lib/promtail/positions
      - ${PWD}/promtail/promtail-config.yaml:/etc/promtail/promtail.yml
    command:
      - '-config.file=/etc/promtail/promtail.yml'
    networks:
      - monitoring

networks:
  nginx_wordpress:
    name: nginx
  keycloak_network:
  wordpress_db:
  monitoring:
    name: monitoring-net

volumes:
  db_data:
  postgres_data:
  promtail-data: {}
