apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:5000
    access: proxy
    isDefault: true
    uid: pls_prometheus

  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: false
