apiVersion: 1
groups:
  - orgId: 1
    name: alerts
    folder: Alert-rules
    interval: 30s
    rules:
      - uid: be53v02gkq1vka
        title: CPU over 70%
        condition: C
        for: 5m # Продолжительность, в течение которой условие должно быть истинным
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: pls_prometheus # Заменено на правильный UID Prometheus
            model:
              editorMode: code
              expr: 100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[3m])) by (instance) * 100)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 70
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    params: []
                    type: last
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        isPaused: false
        notification_settings:
          receiver: Alerting
